create activities, navigation
VPolikushin94/Playlist_Maker pull request #1
Opened 2023-04-01 11:01 UTC by VPolikushin94

2023-04-01 23:13 UTC, NoDopezzz requested changes

2023-04-01 23:13 UTC, NoDopezzz commented on app/src/main/res/layout/activity_settings.xml
> +        android:textAllCaps="false"
⏫ `android:textAllCaps=false` по умолчанию, так что отдельно прописывать этот атрибут необязательно

2023-04-01 23:13 UTC, NoDopezzz commented on app/src/main/res/layout/activity_settings.xml
> +        android:insetTop="0dp"
⏫ В данном случае атрибуты `insetTop` и `insetBottom` - лишние

2023-04-01 23:13 UTC, NoDopezzz commented on app/src/main/res/values/dimens.xml
> +    <dimen name="text_size_22">22sp</dimen>
⏫ Советую именовать ресурсные значения не по "что они из себя представляют", а "где они используются"
Например, `text_size_22` может называться `MainButtonTextSize`.
Также если другой элемент имеет такой же размер, то для него можно завести отдельное значение в ресурсах.

Таким образом
- мы будем понимать, где используется то или иное значение только по его названию
- при необходимости изменить это значение нам не придется ходить по коду и смотреть, какие элементы также используют это значение

2023-04-06 15:39 UTC, VPolikushin94 commented on app/src/main/res/layout/activity_settings.xml
> +        android:textAllCaps="false"
У меня почему-то по умолчанию стоит true и все пишется заглавными буквами

2023-04-06 15:41 UTC, VPolikushin94 commented on app/src/main/res/layout/activity_settings.xml
> +        android:insetTop="0dp"
Эти атрибуты были равны 6dp по умолчанию, соответственно появляются синие полосы снизу и сверху

2023-04-07 01:57 UTC, NoDopezzz approved these changes

2023-04-23 12:21 UTC, merged